name: CI
on:
    - push
    - pull_request
jobs:
    build:
        strategy:
            matrix:
                dependencies:
                    - highest
                    - lowest
                php-versions:
                    - 7.3
                    - 7.4
                    - 8.0
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}

            -   name: Install dependencies with Composer
                uses: ramsey/composer-install@v1
                with:
                    dependency-versions: ${{ matrix.dependencies }}

            -   name: Run unit tests
                run: vendor/bin/phpunit
